---
- name: show running-config
  hosts: AP-ASR99K-CORE-1
  gather_facts: false
  connection: local

  tasks:
    - name: running
      cisco.ios.ios_command:
        commands:
          - show run
          - show ip int brief

      register: print_output

    -  debug: var=print_output.stdout_lines
